### ISSUE TITLE
Wallet won't load after host reboot

### ISSUE THREAD

**Issue by fractalyse** [absolute-community/Absolute-Combine#15]
### Describe the issue
Node won't load wallet after a host reboot

#### If so, please list the steps to reproduce below:
1. Install daemon
2. Run and wait for daemon to be synced
3. Then, Reboot node (host) and restart daemon

### Expected behaviour
Wallet should load.

### Actual behaviour
Wallet stuck at : Loading wallet... (99.90 %)

### What version of Absolute core are you using?
Latest binary release 12.2.5

### Machine specs:
- OS: Ubuntu 16.04
- CPU: 4
- RAM: 2G
- Disk size: 20G
- Disk Type (HD/SDD): HD

### Any extra information that might be useful in the debugging process.

> 2019-04-17 13:44:28 mapAddressBook.size() = 1
> 2019-04-17 13:44:28 Reindexing block file blk00000.dat...
> 2019-04-17 13:44:28 ERROR: AcceptBlock: bad-cb-height, block height mismatch in coinbase (code 16)
> 2019-04-17 13:44:28 ERROR: AcceptBlockHeader: prev block invalid
> 2019-04-17 13:44:47 Reindexing block file blk00001.dat...
> 2019-04-17 13:45:44 Reindexing block file blk00002.dat...
> 2019-04-17 13:45:50 Reindexing finished
> 2019-04-17 13:45:50 Initializing databases...
> 2019-04-17 13:45:50 Pre-allocating up to position 0x1000000 in blk00000.dat
> 2019-04-17 13:45:51 Failed to open mempool file from disk. Continuing anyway.

Actually nothing happends after this error. Don't even sync.

**Comment by CryptoCentric** [comment]
This problem is based around hashing power requirements and can be closed

**Comment by fractalyse** [comment]
One year later..
