### ISSUE TITLE
Sentinel for Windows 10 x64

### ISSUE THREAD

**Issue by alexiv732** [absolute-community/Absolute-Combine#20]
Hi!! Probably configured correctly, but there is no connection to the wallet ??? I do not understand....
`E:\WALLETS\ABSolute>sentinel-win64.exe --config=absolute.conf --rpc-port 18889
Using absolute.conf: absolute.conf
Select an option:
        1. Start sentinel
        2. Fix wallet and masternode

Press 1 or 2. Sentinel will automatically start in 27s

Sentinel runs every 1 minute
2020-02-07 22:04 Running sentinel
Invalid Masternode Status, cannot continue.`

**Comment by Billi7676** [comment]
Hi mate! 
Acctualy it does connect to the wallet... you will get another error if it doesn't (no rpc conn...)
What happen when you start the masternode from wallet?

**Comment by alexiv732** [comment]
masternode start-alias MN1:
{
  "alias": "MN1",
  "result": "successful"
}
Status PRE_ENABLED
masternode status:

{
  "outpoint": "0000000000000000000000000000000000000000000000000000000000000000-4294967295",
  "service": "11.11.11.11:18888",
  "status": "Not capable masternode: Could not connect to 11.11.11.11:18888"
}
E:\WALLETS\ABSolute>sentinel-win64.exe --config=absolute.conf
Using absolute.conf: absolute.conf
Select an option:
        1. Start sentinel
        2. Fix wallet and masternode

Press 1 or 2. Sentinel will automatically start in 29s

Sentinel runs every 1 minute
2020-02-07 23:25 Running sentinel
Invalid Masternode Status, cannot continue.

The same story....(

**Comment by Billi7676** [comment]
i think your configuration is wrong... 
check wiki for how to setup a masternode and sentinel on windows:
https://github.com/absolute-community/absolute/wiki

**Comment by alexiv732** [comment]
))From WIKI:
3.Edit wallet configuration
In your wallet go to tools and then open wallet configuration file.
Empty file will appear, you should copy and paste following code:
masternode=1
masternodeprivkey=[result of masternode genkey]
externalip=your external ip.

[Errno 10061]
Cannot connect to absoluted. Please ensure absoluted is running and the JSONRPC port is open to Sentinel.
?????
the port is open, checked ...
My absolute.conf:
upnp=1
#rpcuser=user
#rpcpassword=user
#server=1
#daemon=1
#listen=1
rpcport=18889
rpcallowip=127.0.0.1
#onlynet=ipv4
masternode=1
masternodeprivkey=keyexample
externalip=11.11.11.11:18888
addnode=192.3.112.76:18888
addnode=37.187.186.215:18888
addnode=45.32.31.50:18888

6.Install the sentinel
According to the instructions at installing sentinel on windows
then the page opens...
Installing Sentinel (V1.2) on Linux

**Comment by Billi7676** [comment]
ok mate... look that the things posted below are in order on your setup...

* make sure that the wallet is using the config files (both absolute.conf and masternode.conf) you edit... i see that you changed the default paths
* better use absolute paths in sentinel.conf or in arguments passed to sentinel
* check the absolute.conf file to have at least theese option enabled:
rpcuser=abs_user
rpcpassword=ABS_pass
rpcallowip=127.0.0.1
rpcport=18889
server=1
listen=1
daemon=1
masternode=1
masternodeprivkey=abs_mn_pk
externalip=xxx.xxx.xxx.xxx
addnode=80.211.181.202:18888
addnode=80.211.60.106:18888
addnode=80.211.168.141:18888
addnode=80.211.155.28:18888
addnode=45.76.195.193:18888
addnode=45.76.195.193:18888
addnode=207.148.6.39:18888
addnode=209.222.30.6:18888

* make sure externalip is your real public ip (188.115.184.253) in both conf files, not that 11...
* make sure that the line in masternode.conf is in correct format (mn_alias ext_ip:18888 abs_mn_pk transaction_id output_index)
* after you modify the conf files always restart the wallet so they are reloaded
* when you start your mn make sure the wallet is synced with the network (last block is the same as the one on explorer.absolutecoin.net)
* check debug.log (wallet > tools > information > debug.log) for any errors.

Also, move this discussion to support channel in discord... this is not an issue with the absolute wallet or daemon...

**Comment by alexiv732** [comment]
Hi!!
masternode status:
 {   "outpoint": "0000000000000000000000000000000000000000000000000000000000000000-4294967295",   "service": "188.115.184.253:18888",   "status": "Not capable masternode: Could not connect to 188.115.184.253:18888" }

Sentinel:
E:\WALLETS\ABSolute>sentinel-win64.exe --config=absolute.conf
Using absolute.conf: absolute.conf
Select an option:
        1. Start sentinel
        2. Fix wallet and masternode

Press 1 or 2. Sentinel will automatically start in 27s

Sentinel runs every 1 minute
2020-02-08 21:29 Running sentinel
Invalid Masternode Status, cannot continue.
2020-02-08 21:30 Running sentinel
Invalid Masternode Status, cannot continue.
2020-02-08 21:31 Running sentinel
Invalid Masternode Status, cannot continue.
2020-02-08 21:32 Running sentinel
Invalid Masternode Status, cannot continue.

Nothing changes(((

**Comment by alexiv732** [comment]
getinfo
{
  "version": 120205,
  "protocolversion": 70210,
  "walletversion": 61000,
  "balance": 2549.98999174,
  "privatesend_balance": 0.00000000,
  "blocks": 568471,
  "timeoffset": 1,
  "connections": 21,
  "proxy": "",
  "difficulty": 537.3086862095539,
  "testnet": false,
  "keypoololdest": 1580381946,
  "keypoolsize": 999,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": ""
}

**Comment by Billi7676** [comment]
is your firewall on?

**Comment by alexiv732** [comment]
in .log &&
GUI: libpng warning: iCCP: known incorrect sRGB profile
GUI: libpng warning: iCCP: known incorrect sRGB profile

**Comment by alexiv732** [comment]
Yes! But port is open...

**Comment by alexiv732** [comment]
in .log
receive version message: /Absolute Core:0.12.2.3/: version 70209, blocks=396248, us=188.115.184.253:59383, peer=44
receive version message: /Absolute Core:0.12.2.5/: version 70210, blocks=568471, us=188.115.184.253:59396, peer=45

receive version message: /Absolute Core:0.12.2.3/
receive version message: /Absolute Core:0.12.2.5/
??????

**Comment by Billi7676** [comment]
disable firewall first... and try again...

**Comment by alexiv732** [comment]
open in discord....
https://discord.gg/xBEKw9

**Comment by CryptoCentric** [comment]
Not heard anything further from this so we will be closing this issue for the time being. Please update to v12.3.1 whenever possible
